version: "3"

services:
  python-kfc:
    container_name: python-kfc
    image: kylebrothers/found-api-2024:latest
    ports:
      - 8888:8888
    restart: unless-stopped
    volumes:
      - /home/kyle/Dropbox/Kevin/KFC_Model/KFC/:/tf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
